# version: '3'

# services:

#   web:

#     build:
#     #command: python manage.py runserver 0.0.0.0:8000
      
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     entrypoint: '/app/entrypoint.sh'
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Assurez-vous de spécifier le chemin correct vers votre Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: '/app/entrypoint.sh'
