# Generated by Django 3.2.20 on 2023-11-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdoc', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
