# Generated by Django 3.2.20 on 2023-11-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0003_alter_documentform_typedoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentform',
            name='typedoc',
        ),
    ]
