# Generated by Django 3.2.20 on 2023-11-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0004_remove_documentform_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentform',
            name='nomdoc',
            field=models.CharField(max_length=254),
        ),
    ]
