# Generated by Django 3.2.20 on 2023-11-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0005_alter_documentform_nomdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentform',
            name='nomdoc',
            field=models.FileField(upload_to=''),
        ),
    ]
