# Generated by Django 3.2.20 on 2023-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0008_alter_documentform_nomdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdoc', models.FileField(null=True, upload_to='public')),
                ('auteur', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'documentverification',
            },
        ),
        migrations.RenameModel(
            old_name='DocumentForm',
            new_name='Document',
        ),
    ]
