# Generated by Django 3.2.20 on 2023-12-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0010_rapport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rapport',
            table='rapport',
        ),
    ]
