# Generated by Django 3.2.20 on 2023-12-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiatLocal', '0011_alter_rapport_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='idtest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='ratio',
            field=models.IntegerField(),
        ),
    ]
